#
# Makefile
#

arrayList: arrayList.cpp
	clang++ -ggdb3 -O0 -std=c++11 -Wall -Werror -o arrayList arrayList.cpp

structs: structs.cpp
	clang++ -ggdb3 -O0 -std=c++11 -Wall -Werror -o structs structs.cpp

trie: trie.cpp
	clang++ -ggdb3 -O0 -std=c++11 -Wall -Werror -o trie trie.cpp

clean:
	rm -f *.o a.out core arrayList structs trie
